version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: condominium
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database_backup.sql:/docker-entrypoint-initdb.d/backup.sql  # Auto-importa en primera ejecución
    ports:
      - "5432:5432"
    networks:
      - condominium_network

  web:
    build: .
    environment:
      - DEBUG=False
      - SECRET_KEY=your-secret-key-for-docker
      - DB_HOST=db
      - DB_NAME=condominium
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_PORT=5432
      - LOAD_INITIAL_DATA=false  # false porque usamos backup
      - ALLOWED_HOSTS=localhost,127.0.0.1
      - CORS_ALLOWED_ORIGINS=http://localhost:3000,http://localhost:5173
    ports:
      - "8000:8000"
    depends_on:
      - db
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
    networks:
      - condominium_network
    restart: unless-stopped

  # Opcional: Nginx para servir archivos estáticos
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - static_volume:/var/www/static
    depends_on:
      - web
    networks:
      - condominium_network

volumes:
  postgres_data:
  static_volume:

networks:
  condominium_network:
    driver: bridge